def fresh_records():
    return (
        'POSTURE=W1\nFINDING flags=- target=U1\nVECTOR V1 surface=U1 severity=78\nVECTOR V2 surface=U1 severity=111\n',
        'POSTURE=W1\nFINDING flags=exploited,unreachable target=U4\nVECTOR V4 surface=U2 severity=164\nVECTOR V1 surface=U1 severity=12\nVECTOR V3 surface=U4 severity=72\nVECTOR V5 surface=U3 severity=122\nVECTOR V2 surface=U2 severity=74\n',
        'POSTURE=W1\nFINDING flags=unreachable target=U1\nVECTOR V2 surface=U1 severity=238\nVECTOR V1 surface=U3 severity=258\nVECTOR V4 surface=U5 severity=132\nVECTOR V3 surface=U4 severity=29\n',
        'POSTURE=W1\nFINDING flags=internal target=U2\nVECTOR V1 surface=U2 severity=184\nVECTOR V2 surface=U4 severity=16\n',
        'POSTURE=W1\nFINDING flags=exploited,internal target=U2\nVECTOR V1 surface=U2 severity=95\nVECTOR V2 surface=U4 severity=100\n',
        'POSTURE=W1\nFINDING flags=unreachable target=U5\nVECTOR V1 surface=U5 severity=161\nVECTOR V2 surface=U1 severity=35\n',
        'POSTURE=W1\nFINDING flags=internal target=U4\nVECTOR V3 surface=U4 severity=231\nVECTOR V4 surface=U4 severity=143\nVECTOR V1 surface=U2 severity=96\nVECTOR V2 surface=U3 severity=93\n',
        'POSTURE=W1\nFINDING flags=exploited,internal target=U1\nVECTOR V2 surface=U1 severity=153\nVECTOR V1 surface=U3 severity=74\nVECTOR V3 surface=U4 severity=41\n',
        'POSTURE=W1\nFINDING flags=- target=U3\nVECTOR V2 surface=U1 severity=85\nVECTOR V1 surface=U3 severity=118\n',
        'POSTURE=W1\nFINDING flags=- target=U2\nVECTOR V2 surface=U4 severity=82\nVECTOR V1 surface=U2 severity=153\nVECTOR V5 surface=U1 severity=93\nVECTOR V4 surface=U1 severity=150\nVECTOR V3 surface=U1 severity=5\n',
        'POSTURE=W1\nFINDING flags=internal,unreachable target=U4\nVECTOR V4 surface=U5 severity=161\nVECTOR V1 surface=U4 severity=241\nVECTOR V2 surface=U2 severity=88\nVECTOR V3 surface=U5 severity=142\nVECTOR V5 surface=U2 severity=248\n',
        'POSTURE=W1\nFINDING flags=internal,unreachable target=U3\nVECTOR V4 surface=U1 severity=237\nVECTOR V1 surface=U3 severity=155\nVECTOR V3 surface=U2 severity=102\nVECTOR V2 surface=U1 severity=206\n',
        'POSTURE=W1\nFINDING flags=- target=U1\nVECTOR V1 surface=U1 severity=11\nVECTOR V2 surface=U3 severity=51\n',
        'POSTURE=W1\nFINDING flags=- target=U3\nVECTOR V1 surface=U3 severity=258\nVECTOR V2 surface=U1 severity=105\n',
        'POSTURE=W1\nFINDING flags=exploited target=U4\nVECTOR V2 surface=U4 severity=156\nVECTOR V1 surface=U2 severity=57\nVECTOR V4 surface=U1 severity=185\nVECTOR V3 surface=U2 severity=212\nVECTOR V5 surface=U5 severity=97\n',
        'POSTURE=W1\nFINDING flags=- target=U1\nVECTOR V2 surface=U3 severity=87\nVECTOR V1 surface=U1 severity=127\n',
        'POSTURE=W1\nFINDING flags=exploited,unreachable target=U3\nVECTOR V5 surface=U2 severity=203\nVECTOR V1 surface=U2 severity=7\nVECTOR V3 surface=U4 severity=205\nVECTOR V4 surface=U4 severity=74\nVECTOR V2 surface=U4 severity=46\n',
        'POSTURE=W1\nFINDING flags=exploited target=U5\nVECTOR V1 surface=U3 severity=158\nVECTOR V3 surface=U5 severity=160\nVECTOR V2 surface=U3 severity=135\n',
        'POSTURE=W1\nFINDING flags=internal target=U2\nVECTOR V4 surface=U5 severity=15\nVECTOR V2 surface=U1 severity=34\nVECTOR V1 surface=U1 severity=199\nVECTOR V5 surface=U3 severity=32\nVECTOR V3 surface=U1 severity=151\n',
        'POSTURE=W2\nFINDING flags=exploited target=U3\nVECTOR V1 surface=U1 severity=71\n',
        'POSTURE=W2\nFINDING flags=- target=U3\nVECTOR V1 surface=U3 severity=146\nVECTOR V4 surface=U5 severity=212\nVECTOR V3 surface=U3 severity=198\nVECTOR V2 surface=U1 severity=71\n',
        'POSTURE=W2\nFINDING flags=exploited target=U2\nVECTOR V3 surface=U1 severity=17\nVECTOR V4 surface=U4 severity=53\nVECTOR V1 surface=U2 severity=240\nVECTOR V2 surface=U4 severity=193\n',
        'POSTURE=W2\nFINDING flags=exploited,unreachable target=U2\nVECTOR V2 surface=U5 severity=259\nVECTOR V1 surface=U5 severity=211\nVECTOR V4 surface=U2 severity=168\nVECTOR V3 surface=U4 severity=162\nVECTOR V5 surface=U3 severity=53\n',
        'POSTURE=W2\nFINDING flags=- target=U4\nVECTOR V2 surface=U2 severity=231\nVECTOR V1 surface=U4 severity=178\n',
        'POSTURE=W2\nFINDING flags=unreachable target=U1\nVECTOR V1 surface=U4 severity=27\nVECTOR V4 surface=U1 severity=136\nVECTOR V3 surface=U3 severity=229\nVECTOR V2 surface=U4 severity=19\n',
        'POSTURE=W2\nFINDING flags=- target=U5\nVECTOR V1 surface=U5 severity=159\n',
        'POSTURE=W2\nFINDING flags=exploited,unreachable target=U4\nVECTOR V2 surface=U5 severity=132\nVECTOR V1 surface=U4 severity=194\nVECTOR V3 surface=U4 severity=199\nVECTOR V5 surface=U5 severity=10\nVECTOR V4 surface=U4 severity=38\n',
        'POSTURE=W2\nFINDING flags=unreachable target=U4\nVECTOR V3 surface=U3 severity=88\nVECTOR V1 surface=U1 severity=79\nVECTOR V2 surface=U3 severity=133\n',
        'POSTURE=W2\nFINDING flags=exploited,internal target=U5\nVECTOR V3 surface=U1 severity=227\nVECTOR V1 surface=U1 severity=105\nVECTOR V2 surface=U5 severity=145\n',
        'POSTURE=W2\nFINDING flags=- target=U5\nVECTOR V2 surface=U5 severity=242\nVECTOR V1 surface=U5 severity=79\n',
        'POSTURE=W2\nFINDING flags=internal target=U4\nVECTOR V1 surface=U5 severity=47\nVECTOR V5 surface=U1 severity=97\nVECTOR V3 surface=U3 severity=88\nVECTOR V2 surface=U3 severity=3\nVECTOR V4 surface=U3 severity=61\n',
        'POSTURE=W2\nFINDING flags=exploited target=U3\nVECTOR V1 surface=U1 severity=54\n',
        'POSTURE=W2\nFINDING flags=unreachable target=U3\nVECTOR V4 surface=U4 severity=137\nVECTOR V3 surface=U3 severity=247\nVECTOR V1 surface=U3 severity=119\nVECTOR V5 surface=U3 severity=145\nVECTOR V2 surface=U1 severity=127\n',
        'POSTURE=W2\nFINDING flags=exploited,unreachable target=U2\nVECTOR V3 surface=U1 severity=123\nVECTOR V1 surface=U2 severity=231\nVECTOR V2 surface=U4 severity=111\n',
        'POSTURE=W2\nFINDING flags=exploited target=U3\nVECTOR V1 surface=U1 severity=155\n',
        'POSTURE=W2\nFINDING flags=exploited,internal,unreachable target=U1\nVECTOR V1 surface=U3 severity=62\nVECTOR V3 surface=U1 severity=25\nVECTOR V4 surface=U1 severity=7\nVECTOR V2 surface=U3 severity=74\n',
        'POSTURE=W2\nFINDING flags=exploited target=U3\nVECTOR V2 surface=U3 severity=218\nVECTOR V3 surface=U2 severity=59\nVECTOR V1 surface=U3 severity=230\nVECTOR V4 surface=U2 severity=203\n',
        'POSTURE=W3\nFINDING flags=- target=U4\nVECTOR V2 surface=U4 severity=29\nVECTOR V3 surface=U2 severity=157\nVECTOR V1 surface=U4 severity=149\nVECTOR V4 surface=U1 severity=49\n',
        'POSTURE=W3\nFINDING flags=exploited target=U1\nVECTOR V2 surface=U3 severity=4\nVECTOR V5 surface=U3 severity=196\nVECTOR V1 surface=U4 severity=189\nVECTOR V4 surface=U5 severity=243\nVECTOR V3 surface=U1 severity=30\n',
        'POSTURE=W3\nFINDING flags=internal target=U5\nVECTOR V3 surface=U5 severity=131\nVECTOR V1 surface=U5 severity=36\nVECTOR V2 surface=U3 severity=114\n',
        'POSTURE=W3\nFINDING flags=internal,unreachable target=U3\nVECTOR V1 surface=U3 severity=146\nVECTOR V2 surface=U1 severity=69\n',
        'POSTURE=W3\nFINDING flags=- target=U1\nVECTOR V1 surface=U1 severity=155\n',
        'POSTURE=W3\nFINDING flags=- target=U5\nVECTOR V1 surface=U1 severity=3\n',
        'POSTURE=W3\nFINDING flags=exploited,unreachable target=U3\nVECTOR V1 surface=U1 severity=202\n',
        'POSTURE=W3\nFINDING flags=- target=U5\nVECTOR V2 surface=U5 severity=151\nVECTOR V3 surface=U4 severity=191\nVECTOR V1 surface=U5 severity=121\n',
        'POSTURE=W3\nFINDING flags=exploited,unreachable target=U2\nVECTOR V5 surface=U5 severity=47\nVECTOR V4 surface=U5 severity=231\nVECTOR V2 surface=U2 severity=123\nVECTOR V3 surface=U4 severity=52\nVECTOR V1 surface=U4 severity=113\n',
        'POSTURE=W3\nFINDING flags=exploited target=U2\nVECTOR V3 surface=U2 severity=56\nVECTOR V1 surface=U1 severity=35\nVECTOR V2 surface=U2 severity=200\n',
        'POSTURE=W3\nFINDING flags=- target=U5\nVECTOR V2 surface=U1 severity=191\nVECTOR V1 surface=U1 severity=166\n',
        'POSTURE=W3\nFINDING flags=- target=U3\nVECTOR V1 surface=U1 severity=258\n',
        'POSTURE=W3\nFINDING flags=internal,unreachable target=U3\nVECTOR V2 surface=U5 severity=73\nVECTOR V5 surface=U4 severity=141\nVECTOR V3 surface=U5 severity=160\nVECTOR V1 surface=U5 severity=192\nVECTOR V4 surface=U5 severity=144\n',
        'POSTURE=W3\nFINDING flags=- target=U5\nVECTOR V1 surface=U5 severity=59\n',
        'POSTURE=W3\nFINDING flags=internal target=U5\nVECTOR V3 surface=U4 severity=236\nVECTOR V2 surface=U3 severity=209\nVECTOR V1 surface=U2 severity=148\n',
        'POSTURE=W3\nFINDING flags=- target=U1\nVECTOR V1 surface=U3 severity=71\nVECTOR V3 surface=U3 severity=135\nVECTOR V2 surface=U5 severity=22\n',
        'POSTURE=W3\nFINDING flags=exploited,internal target=U4\nVECTOR V1 surface=U4 severity=190\nVECTOR V3 surface=U4 severity=48\nVECTOR V4 surface=U4 severity=23\nVECTOR V2 surface=U1 severity=128\n',
        'POSTURE=W3\nFINDING flags=exploited target=U5\nVECTOR V3 surface=U3 severity=228\nVECTOR V1 surface=U5 severity=84\nVECTOR V2 surface=U5 severity=86\n',
        'POSTURE=W3\nFINDING flags=unreachable target=U1\nVECTOR V3 surface=U2 severity=214\nVECTOR V1 surface=U3 severity=60\nVECTOR V2 surface=U2 severity=66\n',
        'POSTURE=W3\nFINDING flags=exploited target=U2\nVECTOR V3 surface=U4 severity=41\nVECTOR V4 surface=U5 severity=33\nVECTOR V2 surface=U1 severity=91\nVECTOR V5 surface=U2 severity=75\nVECTOR V1 surface=U1 severity=206\n',
        'POSTURE=W3\nFINDING flags=- target=U1\nVECTOR V3 surface=U1 severity=68\nVECTOR V1 surface=U1 severity=39\nVECTOR V4 surface=U3 severity=44\nVECTOR V2 surface=U5 severity=8\n',
    )
